# Generated by Django 3.2.5 on 2023-05-23 15:31

import carrental.xor_relationship
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("origin_country", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("rented", "Rented"),
                            ("service", "Service"),
                            ("pending", "Pending"),
                        ],
                        default="free",
                        max_length=15,
                    ),
                ),
                ("plate", models.CharField(max_length=20, unique=True)),
                ("insurance_start_date", models.DateTimeField(null=True)),
                ("insurance_end_date", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("driving_license", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=50, unique=True)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=10, null=True, unique=True)),
                ("country", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("telephone", models.CharField(max_length=10, null=True, unique=True)),
                ("ac", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_per_hour", models.PositiveIntegerField()),
                ("price_per_kilometer", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rental_status",
                    models.CharField(
                        choices=[
                            ("finished", "Finished"),
                            ("ongoing", "Ongoing"),
                            ("booked", "Booked"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "car_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrental.car",
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrental.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RepairWorkshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("telephone", models.CharField(max_length=10, null=True, unique=True)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TrafficViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fine", models.PositiveIntegerField(null=True)),
                ("description", models.TextField(max_length=250)),
                ("penalty_points", models.PositiveIntegerField(null=True)),
                (
                    "rental_id",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrental.rental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                (
                    "rate",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10)]
                    ),
                ),
                (
                    "rental_id",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrental.rental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.PositiveIntegerField(null=True)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                (
                    "insurance_company_id",
                    carrental.xor_relationship.XORForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrental.insurancecompany",
                    ),
                ),
                (
                    "repair_workshop_id",
                    carrental.xor_relationship.XORForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrental.repairworkshop",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rental",
            name="station_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carrental.rentalstation",
            ),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(null=True)),
                ("description", models.TextField(max_length=250, null=True)),
                ("apologise_message", models.TextField(max_length=250, null=True)),
                (
                    "rental_id",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrental.rental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("seats_number", models.PositiveIntegerField()),
                ("trunk_capacity", models.PositiveIntegerField(null=True)),
                ("doors_number", models.PositiveIntegerField()),
                ("produced_date", models.DateField(blank=True, null=True)),
                (
                    "brand_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrental.brand",
                    ),
                ),
                (
                    "price_list_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrental.pricelist",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrental.cartype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarFault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=250)),
                (
                    "repair_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrental.repair",
                    ),
                ),
                (
                    "report_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrental.report",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="car_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="carrental.carmodel",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rental_station_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="carrental.rentalstation",
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "client_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="carrental.client",
                    ),
                ),
                ("pesel", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("second_name", models.CharField(max_length=50)),
                (
                    "parent",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_person",
                        to="carrental.client",
                    ),
                ),
            ],
            bases=("carrental.client",),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "client_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="carrental.client",
                    ),
                ),
                ("nip", models.CharField(max_length=50, unique=True)),
                ("sector", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_company",
                        to="carrental.client",
                    ),
                ),
            ],
            bases=("carrental.client",),
        ),
    ]
