# Generated by Django 4.2 on 2023-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("carrental", "0003_alter_repairworkshop_telephone")]

    operations = [
        migrations.AlterField(
            model_name="client", name="password", field=models.CharField(max_length=64)
        )
    ]
